# Enquêtevragen

## Zorgen

**Wat zijn tot nog toe de grootste zorgen en vraagstukken van uw examencommissie in de Corona-periode geweest? Kunt u daarbij aangeven welke daarvan nog steeds spelen?**

Verreweg de meeste respondenten noemen tussen de drie en vijf kwesties die hun zorgen baren. Absolute koploper is de fraude. Daarna komen de toetskwaliteit resp. de kwestie van de alternatieve toetsvormen en de kwaliteit van de online proctoring. Deze top 4 is nauw verbonden met de wettelijke taak van de examencommissie. Ook is er zorg over de werkdruk, niet alleen over die bij de examencommissies zelf, maar ook onder docenten/examinatoren en ondersteuning.  

De onderstaande tabel geeft een overzicht: 

Zorgpunten | aantal
-----------|-------
Fraude | 70 
Toetskwaliteit | 42 
Werkdruk bij examencommissie, docenten en ondersteuning | 29 
Kwaliteit online proctoring en technische problemen | 27 
Alternatieve toetsvorm | 15 
Onmogelijkheid van praktijkonderwijs en bijbehorende toetsing | 14 
Technische problemen bij toetsen op afstand | 9 
Privacy-aspecten surveillance | 9 
Geestesgesteldheid studenten | 8 
Privacy-aspect bij online proctoring | 9 
Check op identiteit | 4 

Vrijwel alle kwesties blijven een punt van zorg, met enkele uitzonderingen: 

* Inmiddels vinden toetsing weer doorgang, nadat zij aanvankelijk uitgesteld waren. 
* Een deel van de problemen met het vinden van een passende alternatieve toetsvorm waarmee de beoogde leeruitkomsten op een valide wijze getoetst kunnen worden, lijkt opgelost te zijn. 


## Extra aandacht na corona

**Welke aspecten van toetsing op afstand behoeven na de Corona-periode nog extra aandacht van uw examencommissie en wat is de reden hiervoor?**

De antwoorden op deze vraag vertonen een aanzienlijke diversiteit. Een relatief groot aantal examencommissies (…) geeft aan dat zij hun werk willen kunnen doen binnen een infrastructuur waarin voldaan is aan belangrijke randvoorwaarden. Bij sommige instellingen is het toetsen op afstand nog onvoldoende verankerd in het toetsbeleid en ontbreken nog heldere protocollen die bijvoorbeeld specificeren hoe moet worden omgegaan met de complicaties die zich bij afname van toetsen op afstand kunnen voordoen. Enkele commissies uiten hun zorg erover dat zij in het kader van de borging nog voor verrassingen kunnen komen te staan, als zij er in het kader van de borging aan toe zijn de onder invloed van Corona aangepaste toetsing door te lichten. Veel examencommissies hebben fraudepreventie hoog op de agenda staan en zouden graag zien dat er in de toekomst een verantwoorde afweging gemaakt zal worden of online proctoring ingezet kan worden. Scepsis over online proctoring klinkt in veel antwoorden door, onder meer vanwege de privacy-gevoeligheid ervan, de stress die studenten erdoor zeggen te ervaren, de bewerkelijkheid van de detectie, de bewijsproblematiek en de technische onvolmaaktheden. Voorlopig lijken examencommissies meer te zien in aanpassing van de toetsvorm, indien op afstand wordt getoetst of in inzetten op toetsing op locatie. Examencommissies uiten soms ook zorg omtrent zaken waarvoor zij geen directe verantwoordelijkheid hebben, zoals ten aanzien van inzage in gemaakte toetsen die nauwelijks te organiseren is zonder het risico te lopen dat de toets op straat komt te liggen. Ook zien zij achterstanden die studenten buiten hun schuld hebben opgelopen en die met een ongewijzigd herkansingsbeleid niet goed in te lopen zijn. 

## Invloed besluitvorming

**Op welke wijze heeft uw examencommissie bemoeienis gehad met besluitvorming over aanpassingen in de toetsing (bijvoorbeeld leerdoelen, af- of uitstel van toetsing, alternatieve toetsvorm, gewijzigde afnamecondities, aanwijzingen voor examinatoren)?**

De vraag is gesteld om te achterhalen of examencommissies een actieve rol hebben gespeeld in het implementeren van aanpassingen. Slecht 5 examencommissies geven aan, geen of nauwelijks enige bemoeienis te hebben gehad met aanpassingen. Vooral met betrekking tot aanpassingen van de toetsvorm en (in voorkomende gevallen) de leerdoelen is de betrokkenheid van de examencommissies groot geweest: grofweg de helft van de commissies geeft aan dat het hierbij zelfs om expliciete toestemming ging. De andere helft geeft aan dat er sprake is geweest van een afstemmingsproces. In een enkel geval kreeg dit zelfs de vorm van een formeel mandaat vanuit de medezeggenschap en de opleidingscommissie, hetgeen formeel buitengewoon correct is, aangezien de toetsvorm in de OER vastgelegd is. 

Dit is een opmerkelijke uitkomst, omdat een ontwerp voor een toets onder normale omstandigheden niet langs de examencommissie hoeft, ook al is het altijd mogelijk dat een examencommissie in incidentele gevallen geconsulteerd wordt. 

Ten aanzien van aanpassingen in de afnamecondities is de inbreng van de examencommissies aanzienlijk geringer geweest (zie ook vraag 4). In het overgrote deel van de gevallen zijn examencommissies hierover “slechts” geïnformeerd. Principieel zou ook ten aanzien van de afnamecondities een verdergaande bemoeienis van de examencommissie goed te verdedigen zijn geweest, aangezien de examencommissie ex art. 7.12b, eerste lid, onder e WHW  verantwoordelijkheid draagt ten aanzien van de borging van de kwaliteit van “de organisatie en de procedures rondom tentamens en examens”.  

De gevolgde werkwijze heeft als groot voordeel dat examencommissies zodoende niet voor grote verrassingen komen te staan, als zij na afronding van de toetsing in het kader van de borging terugblikken op de toetsing. Verder kan deze werkwijze ertoe bijdragen dat examinatoren en opleidingen zich effectief ondersteund hebben gevoeld door de examencommissie, waardoor de processen mogelijk soepeler verlopen zijn dan als zij het zonder bemoeienis van deze critical friend hadden moeten stellen.

## Inrichting afname 

**Hoe zorgt uw examencommissie ervoor dat zij in het kader van de borging van de toetskwaliteit op termijn kan beschikken over een beschrijving van de feitelijke inrichting van de toetsing en de feitelijke gang van zaken rond de afname?**

De derde van de respondenten heeft deze vraag niet beantwoord. Ook geven enkele respondenten aan niet goed te begrijpen wat er met de vraag wordt bedoeld. De bedoeling achter de vraag is te achterhalen of examencommissies zich er – niettegenstaande hun bemoeienis “aan de voorkant” met aanpassingen gericht op toetsing op afstand –rekenschap van geven dat zij pas bij de borging van de toetskwaliteit “achteraf” zicht krijgen op hoe de toetsing feitelijk uitgepakt heeft. Mocht dan pas blijken dat bijvoorbeeld een leerdoel onvoldoende tot zijn recht is gekomen in de aangepaste toetsing, kan er in veel gevallen niet meer bijgestuurd worden. Met andere woorden: hoe stringenter examencommissies gemonitord hebben hoe de aanpassingen er precies uitzien, des te kleiner is de kans dat zij achteraf voor een onaangenaam fait accompli gesteld worden. 40 examencommissies geven aan dat een en ander voorafgaand aan de afname vastgelegd is in documenten. 10% heeft haar hoop gevestigd op verslagen van het feitelijke verloop van de toetsing en 10% vertrouwt erop dat dit door middel van gesprekken en e-mail vooraf afdoende inzichtelijk is. 14 respondenten kiezen ervoor hierop in het kader van de borging achteraf zicht op te krijgen. Ca. 20% volgt het verloop van de toetsing op de voet. 

Mogelijk spelen op de achtergrond verschillende opvattingen mee over wat de borging van de toetskwaliteit zou moeten inhouden. Tenslotte wordt het veelal aan de autonome examencommissies zelf overgelaten hoe zij aan deze borging vormgeven. Zo kunnen er verschillen zijn in de mate waarin aspecten van de feitelijke toetsafname meegenomen worden in de borging. Afnameverslagen en bijstellingen van de cesuur op basis van toets- en itemanalyses maken nu eenmaal niet overal deel uit van het dossier dat examencommissies in hun borging doorlichten. 

## Betrouwbaarheid en validiteit 

**In hoeverre wegen de kwaliteitsaspecten ‘validiteit’ en ‘betrouwbaarheid’ van toetsing voor uw examencommissie tijdens Corona even zwaar als daarvóór?**

De vraag is ingegeven door signalen dat de disruptie die door Corona in het hoger onderwijs de kwaliteit van toetsing onder druk zet. Beoordelen blijft nu eenmaal mensenwerk en het is daarom maar al te goed voorstelbaar en tot op zekere hoogte ook verdedigbaar dat voor gerezen problemen met een zekere coulance gereageerd wordt. Waar echter centrale kwaliteitseisen in het geding zijn die dienen te borgen dat de waarde van diploma’s niet gecompromitteerd wordt, is met de toepassing van coulance grote voorzichtigheid geboden.  

Gelukkig acht het overgrote deel (ca. 80%) van de examencommissies zich onverkort gebonden aan de kwaliteitscriteria ‘validiteit’ en ‘betrouwbaarheid’. Als ca. 10% deze criteria zelfs zwaarder laat wegen dan voorheen, moet dit vermoedelijk geduid worden als een teken dat deze examencommissies zich realiseren dat er door aanpassingen in de toetsopzet en door de toetsen in de thuissituatie van de student af te nemen, een afbreukrisico bestaat t.a.v. de kwaliteit. 

De ca. 10% die de kwaliteitscriteria minder zwaar laat wegen, zegt dit te doen om pragmatische redenen. 

## Surveillance

**Op welke wijze heeft uw examencommissiezicht kunnen houden op de introductie van nieuwe vormen van surveillance tijdens toetsen op afstand? Hoe kijkt de examencommissie tegen deze vormen van surveillance aan?**

Onderwijsinstellingen werden in het voorjaar van 2020 ook met het probleem geconfronteerd hoe zij het toezicht tijdens de afname van toetsen op afstand moesten vormgeven. Een centrale pijler onder ons stelsel van hoger onderwijs is het beginsel dat elke student individueel de eindkwalificaties van zijn/haar opleiding gerealiseerd dient te hebben. Onder die voorwaarde kan aan het einde van de opleiding het diploma uitgereikt worden. In de verschillende fasen van de opleiding wordt door middel van toetsen in kaart gebracht of studenten individueel de beoogde leeruitkomsten van studieonderdelen behaald hebben. Doordat successievelijk gewerkt wordt aan leeruitkomsten  van toenemende moeilijkheidsgraad en/of complexiteit komt langzamerhand de realisering van de eindkwalificaties in zicht. Tegen deze achtergrond rust op instellingen de verplichting zich ervoor in te zetten dat de integriteit van de toetsing boven twijfel verheven is. 

Examencommissie hebben in meerderheid gestreefd naar grote bemoeienis met de invoering van nieuwe vormen van surveillance, namelijk surveillance op afstand. De vorm van bemoeienis die hiervoor het vaakst gevonden werd, is die van onderlinge afstemming. Van de ca. 50 respondenten die inhoudelijk antwoord heeft gegeven op de vraag hebben er slechts zeven van de bevraagde examencommissies een toestemmingsprocedure ingevoerd.  

Ook bij toetsing op een toetslocatie van de instelling bestaat het risico dat de afname van de toets gecompromitteerd raakt door een vorm van fraude. Met de overgang naar toetsing op afstand waarbij studenten hun toets in de thuissituatie maken, zagen instellingen gebeuren dat zij door het wegvallen van fysieke surveillance de controle over de afname konden verliezen. Om deze dreiging het hoofd te bieden, zijn soms snel besluiten genomen over een alternatieve vorm van toezicht via de computer. Het gaat dan om identiteitscontrole en om real-time zicht houden op de studenten, bijv. door middel van online conference tools als Teams en Zoom, waarbij een surveillant een kleine groep studenten in de gaten houdt en in directe interactie met een student kan verzoeken om een desk scan. Daarnaast hebben opleidingen het initiatief genomen om steekproefsgewijs studenten na te bellen en zo vooral op preventie in te zetten. Ook zijn instellingen soms een flinke stap verder gegaan om het gedrag van studenten tijdens een toets in de thuissituatie te monitoren. Door middel van de inzet van software als Proctorio of ProctorExam worden bepaalde gedragingen van studenten als verdacht aangemerkt, waarna door een menselijke waarnemer aan de hand van de beelden gecheckt wordt of er inderdaad sprake is van een onregelmatigheid of zelfs van fraude. De inzet van deze laatste soort software heeft voor veel discussie gezorgd, ook in de media. De onderhavige enquêtevraag wordt vermoedelijk om die reden door veel respondenten opgevat als een vraag naar online proctoring. De antwoorden vertonen daardoor een zekere eenzijdigheid. 

Veelal kregen examencommissies in het verleden pas te maken met de wijze van surveilleren, als er iets verkeerd leek te gaan. Vermoedelijk heeft dat ertoe geleid dat examencommissies de kwaliteit van de organisatie van tentamens (waaronder ook surveillance valt) soms als minder prominent bestanddeel van de borging van de kwaliteit van toetsing zijn gaan beschouwen3. De wijze waarop de surveillance tijdens een toetsafname is ingericht, kan potentieel interfereren met de meting en haar betrouwbaarheid ondermijnen. Bijgevolg dient de examencommissie in het kader van haar borgingsinspanningen aandacht te besteden aan de surveillance. Zij dient daarom over adequate informatie te beschikken over de opzet van de surveillance en dient te onderzoeken of, en zo ja, in welke mate de surveillance een bedreiging vormt voor de betrouwbaarheid van de meting. 

Uit de antwoorden op de onderhavige enquêtevraag blijkt dat examencommissies In ieder geval aanzienlijk minder bemoeienis hebben gehand met de besluitvorming over alternatieve surveillance gehad dan met de besluitvorming over alternatieve toetsvormen of leerdoelen. Slechts in enkele gevallen heeft de examencommissie toestemming gegeven voor de toepassing van een alternatieve vorm van surveillance. Covid-19 heeft in dat opzicht dan ook zeker als wake-up call gefunctioneerd. 

Vrijwel geen van de respondenten is onverdeeld positief over online proctoring bij toetsing in de thuissituatie van studenten. De meesten zien het als “noodzakelijk kwaad”. Ook worden regelmatig onvolkomenheden die men in het werken met online proctoring tegenkomt, uitgelicht. Als nadelen ervaart men de AVG-gerelateerde bezwaren, de stress die studenten ervaren, de bewijsproblemen en niet in de laatste plaats de bewerkelijkheid van het beoordelen van de signaleringen.  

Sommigen spreken een duidelijke voorkeur uit voor real-time surveillance met Teams of Zoom, omdat dan nog met een geringe inspanning bijgestuurd kan worden als zich een onregelmatigheid aftekent. Zo wordt in de kiem gesmoord wat had kunnen uitgroeien tot fraude. 

## Voorwaarden online proctoring

**Wat beschouwt uw examencommissie als de belangrijkste voorwaarden voor de (eventuele) inzet van online proctoring?**

Ook bij deze vraag speelt dat de respondenten real-time surveillance met ZOOM of Teams niet als vorm van online proctoring beschouwen. De scepsis van examencommissies over toekomstige, al dan niet brede inzet van online proctoring met programma’s als Proctorio en ProctorExam is ook in de beantwoording van de onderhavige vraag bespeurbaar. 
De antwoorden waaieren breed uit, waarbij voor de meeste respondenten de volgende punten het vaakst genoemd werden als voorwaarden voor de inzet van online proctoring:

*	privacy-kwesties 
*	de effectiviteit van fraudepreventie
*	de bewerkelijkheid van en de problemen met de fraudedetectie
*	goed uitgewerkte protocollen
*	de kosteneffectiviteit
*	aandacht voor het studentperspectief.

## Realisatie eindniveau

**Is uw examencommissie van plan om in het kader van de kwaliteitsborging van het examen extra aandacht te besteden aan de feitelijke realisatie van het eindniveau van de opleiding door studenten? Zo ja, waarom?**

Van de ruim 100 respondenten die deze vraag hebben beantwoord geeft ruim de helft aan dat dit zodanig geïntegreerd is in hun reguliere werkwijze dat de bijzondere omstandigheden rond Covid-19 hieraan niets veranderen. Een krappe helft is wel van plan om hierin een extra inspanning te verrichten. De vormen die het meest gekozen zijn steekproeven, al dan niet als onderdeel van de reguliere borgingsactiviteiten. Een enkele commissie is voornemens om toetsanalyses te gaan bekijken en de recente resultaten met die van eerdere cohorten te vergelijken.
Het beeld dat uit de antwoorden oprijst, is dat van examencommissies die zich zeer bewust zijn van de risico’s die met het toetsen op afstand gepaard gaan.

## Gemiste ondersteuning

**Heeft uw examencommissie met betrekking tot toetsen op afstand tijdens de Corona-pandemie informatie, kennis of ondersteuning gemist waardoor de uitvoering van haar diverse wettelijke taken bemoeilijkt werd? Waarom gaat het u daarbij? Zo ja, wordt dit gemis momenteel nog steeds gevoeld?**

De vraag is door 72 van de 2018 respondenten beantwoord. Van hen heeft iets minder dan de helft het een en ander gemist. Het gemis dat het meest frequent genoemd werd, is de ondersteuning voor de examencommissie (compensatie voor de sterk gestegen werkdruk, ondersteuning op technisch, onderwijskundig en juridisch terrein). Met name op onderwijskundig vlak wordt het gemis ook nu nog gevoeld. De werkdruk is er inmiddels nog niet minder op geworden. Voorts wordt door een aantal examencommissies genoemd dat zij te weinig eenduidige kaders ontvingen van het instellingsbestuur. Hier ziet men echter wel verbetering optreden.

Een kennisachterstand ervoeren examencommissies met name op het gebied van de online proctoring. Van de 15 examencommissies die dit noemen, ervaren er 12 dit gemis nog steeds.

## Fraude door veranderde toetsing

**Is uw examencommissie bepaalde vormen van fraude of pogingen daartoe tegengekomen die deels of volledig voortvloeien uit de veranderde wijze van toeting en/of toetsafname wegens Corona? Zo ja, kunt u voorbeelden noemen?**

De vraag is gericht op gevallen die na onderzoek van de examencommissie naar haar mening aangemerkt konden worden als fraude. Vermoedelijk zijn er daarnaast nog andere gevallen waarin het moeilijk bleek te zijn om de fraude te bewijzen.
Van de ongeveer 120 commissies die deze vraag beantwoord hebben, geeft ongeveer een kwart aan, geen echt Corona-gerelateerde gevallen van fraude te zijn tegengekomen. Driekwart daarentegen zegt deze vormen wel te zijn tegengekomen. De meest frequent waargenomen vorm is het ongeoorloofd samenwerken, ofwel met gebruikmaking van e-mail of sociale media (bijv. WhatsApp-groep) dan wel door te werken in eenzelfde (Google-) document of anderszins documenten uit te wisselen dan wel samen te werken vanaf een en dezelfde fysieke locatie (hetzelfde studentenhuis). Het beeld dat de samenwerking beperkt blijft tot toetsen waarin kennisreproductie een prominente rol speelt, behoeft dus bijstelling. Het voorbeeld van het take-home tentamen toont aan dat gemakkelijk overleg kan worden gevoerd, waarna de studenten hun antwoorden van een persoonlijke touch kunnen voorzien, al dan niet met behulp van parafrase-software.
Een goede tweede plaats wordt ingenomen (ca. 10%) door het raadplegen van niet toegestane bronnen.
Vormen van ongeoorloofde samenwerking via sociale media worden frequenter gezien in het wo dan in het hbo.
Incidenteel wordt melding gemaakt van het fotograferen dan wel het maken van een screenshot van opgaven, een probleem dat ook bij de inzage in afgelegde tentamens speelt. Ook wordt het sjoemelen met tijden (door herhaaldelijk aanmelden of later beginnen, zogenaamd wegens technische storingen te laat inleveren) en het saboteren van de ID-check genoemd.
Met enige regelmaat uiten respondenten hun zorg over de achterstand die instellingen hebben op computervaardige studenten die zich voordelen weten te verschaffen met allerlei applicaties, in-ear koptelefoons en door het gebruik van software waarmee de online proctoring wordt ondermijnd.

## Omgang fraudemeldingen

**Hoe is op dergelijke fraudemeldingen gereageerd (zoals bijvoorbeeld met aanscherping van de preventie, ongeldigverklaring, sanctie, aanpassing fraudebeleid)?**

Deze vraag is door 69 respondenten beantwoord. De maatregelen die vaak in combinatie het meest frequent zijn ingezet, zijn de ongeldigverklaring van de toets van de betreffende student en het opleggen van sancties. Daarvoor hebben examencommissies hun sanctietabel soms aangepast. Niet alleen bij vermeende fraude, maar ook bij geconstateerde onregelmatigheden werd de student gehoord en werden in het geval van bepaalde onregelmatigheden die zich wegens bewijsproblemen niet als fraude lieten kwalificeren, waarschuwingen afgegeven. Slechts een enkele respondent geeft aan dat er in voorkomende gevallen wel coulance betracht is. Verder noemt een aantal respondenten dat hun examencommissie zich sterk gemaakt heeft voor betere communicatie met studenten en betere aansturing van docenten en ook overigens sterker op preventie heeft ingezet.

## Toename fraude

**Is er onder invloed van Corona-maatregelen bij u sprake van een toename van het aantal meldingen van vermeende fraude?**

De vraag is gericht op het achterhalen van de mate waarin mogelijk sprake is van een toename van het aantal fraudemeldingen. Bewust is gekozen voor een focus op meldingen van examinatoren die naar hun mening nader onderzoek door de examencommissie wettigden.
Iets minder dan de helft van de 218 respondenten heeft de vraag beantwoord.
20% geeft aan geen toename te hebben kunnen vaststellen.
Waar wel een toename werd gezien, ging het om de volgende aantallen:

0-10%	| 10-25% | 25-50% | Meer dan 50%
------|--------|--------|-------------
31	  | 15	   | 6	    | 15

Bij deze vraag tekent zich een verschil af tussen hbo en wo. Lichte tot matige stijgingen worden in het hbo relatief iets vaker gezien, terwijl stijgingen van meer dan 50% uitsluitend in het wo gezien worden.
Er zijn geen aanwijzingen dat de bereidheid van docenten om potentiële fraudegevallen te melden, tijdens de Corona-periode groter was dan voordien. Slechts af en toe signaleren respondenten dat de waakzaamheid onder docenten t.a.v. mogelijke fraude voor hun gevoel is toegenomen. Bij het percentage van 20% dat geen stijging van het aantal meldingen heeft vastgesteld, kan het voor een deel gaan om kleinschaliger masteropleidingen waarvan de wijze van toetsen tijdens de Corona-periode niet anders is dan voordien.
De antwoorden van het merendeel van de respondenten maken een verband met de toegenomen werkdruk van examencommissies aannemelijk.

## Fraude gevoelige toetsvormen

**Welke toetsvormen zijn volgens uw examencommissie bij uitstek fraudegevoelig bij toetsing op afstand?**

Drie toetsvormen springen eruit als vormen die het wel heel verleidelijk maken om zich als student op ongeoorloofde wijze een voordeel te verschaffen. Het hoogst scoren de gesloten vragen (93 van de in totaal 113 antwoordende respondenten). Daarna komen de open vragen en de take-home tentamens (elk genoemd door ca. 44 respondenten). 

Ten aanzien van take-home tentamens moet het volgende bedacht worden. Doordat docenten in hoog tempo met een alternatieve toetsvorm moesten komen, toen duidelijk werd dat het fysiek op een toetslocatie afnemen van een toets niet meer tot de mogelijkheden behoorde, was het take-home tentamen een interessante optie, al vergde die dat de opzet van de vragen ingrijpend moest veranderen, om niet uit te komen bij een veel te eenvoudig tentamen waarvan nog maar de vraag zou zijn of het de beoogde leeruitkomsten van het betreffende vak wel voldoende afdekte. Als niettemin voor het alternatief van het take-home tentamen werd gekozen, had dit ook voor studenten ingrijpende consequenties die wellicht niet altijd gezien lijken te worden. Een take-home tentamen lijkt vanuit het student-perspectief wellicht een aantrekkelijk alternatief, omdat men hiermee associeert dat men alle mogelijke bronnen mag gebruiken, zonder zich veel gelegen te laten liggen aan de conventies van integer brongebruik. In de perceptie van studenten valt deze toetsvorm in de categorie ‘tentamen’, een categorie die veel meer vrijheid in de omgang met bronnen lijkt bieden dan bijvoorbeeld een werkstuk, dat als toetsvorm veel minder raakvlakken met een klassiek tentamen heeft. Bij een werkstuk zullen studenten zich daarom vermoedelijk bewuster zijn van de regels van academische integriteit. Als studenten bij take-home tentamens niet uitdrukkelijk gewezen zijn op de regels rond het respecteren van de intellectuele eigendom, kan dit leiden tot het zonder bronvermelding en zonder het gebruik van aanhalingstekens veelvuldig kopiëren van tekst van anderen. Dan is het een kleine stap als de categorie van de “anderen” opgerekt wordt naar medestudenten die bezig zijn met hetzelfde tentamen.

## Behoefte fraudepreventie

**Waaraan heeft uw examencommissie behoefte, als het gaat om fraudepreventie en 
-detectie bij toetsen op afstand?**

De meeste respondenten noemen een waterdichte surveillance als middel om fraude te detecteren als belangrijkste wens. Daarna komt een betere informatievoorziening (eenduidige regelgeving, informatie over digitale mogelijkheden voor online surveillance, uniform sanctiebeleid, uitwisseling van good practices). Voorts worden genoemd: een robuuste, goed in de leeromgeving en/of toetsapplicatie geïntegreerde plagiaatscanner, een oplossing voor het met sociale media uitwisselen van informatie tussen studenten tijdens een toets. Ca. 10% mist niets.
	
## Gewijzigd beleid

**Heeft uw examencommissie als gevolg van de Corona-maatregelen haar eigen beleid ten aanzien van fraude (incl. plagiaat) gewijzigd? Zo ja, in welk opzicht?**

Deze vraag is door ruim 100 respondenten beantwoord. 80% geeft aan haar beleid niet te hebben gewijzigd. Waar dat wel gebeurde ging het om een combinatie van de volgende acties:

*	differentiatie tussen ‘onregelmatigheid’  en ‘fraude’
*	aanpassing sanctietabel aan toetsen op afstand
*	versterkte inzet plagiaatscanner, ook bij kleine schrijfopdrachten
*	coulance wegens onduidelijkheden voor studenten.

## Onregelmatigheid vs fraude

**Hanteert uw examencommissie het onderscheid tussen ‘onregelmatigheid’ en ‘fraude’? Zo ja, wat zijn de gevolgen hiervan in de afhandeling van zaken?**

Een kwart van de 113 respondenten die deze vraag hebben beantwoord, hanteert in de praktijk niet het onderscheid tussen ‘onregelmatigheid’ en ‘fraude’. Uit de antwoorden van deze groep komt incidenteel naar voren dat men dit onderscheid als een “semantische discussie” beschouwt, d.w.z. zonder nuttige implicaties voor de praktijk. Drie kwart maakt het onderscheid wel en voor de meerderheid van deze groep heeft dit kennelijk meteen implicaties voor het al dan niet opleggen van een sanctie: bij bewezen fraude wel, bij onregelmatigheden niet. In dat laatste geval is er dan als maatregel altijd de ongeldigverklaring.

De antwoorden van een relatief grote groep respondenten geven te denken over de mate waarin juridische kennis over het bovengenoemde onderscheid met examinatoren en examencommissies gedeeld is. Onder de categorie ‘onregelmatigheid’ vallen uiteenlopende omstandigheden die eraan in de weg staan, de prestatie van een student te kunnen beschouwen als diens individuele, met gebruik van slechts geoorloofde hulpmiddelen en binnen de gestelde afnameregels tot stand gekomen prestatie. Of in de woorden van het CBHO: “In algemene zin moet fraude dan ook worden onderscheiden van handelen van een student waaruit blijkt dat hij tekortschiet in de eisen die de opleiding stelt om tot een positieve beoordeling van het resultaat te komen.”  Dat in bepaalde gevallen het harde bewijs van fraude niet geleverd kan worden, betekent niet er geen ruimte is voor een andere maatregelen: het ongeldig verklaren van een toets. Zodra de examencommissie heeft geconcludeerd dat het bewijs van fraude niet geleverd kan worden, kan de zaak terugverwezen worden naar de examinator die vervolgens in goed overleg met het opleidingsmanagement tot ongeldigverklaring kan overgaan. Vanzelfsprekend kan in voorkomende gevallen besloten worden tot een gesprek waarin de maatregel toegelicht wordt en de student – indien dit opportuun geacht wordt – gewaarschuwd kan worden voor de gevolgen van toekomstige door hem of haar (mede) veroorzaakte onregelmatigheden.
Belangrijk te vermelden is hierbij dat er geen sprake kan zijn van frauduleus handelen “als het niet als zodanig kenbaar is”. Het dient dan ook altijd om een geschreven regel te gaan, wat echter omgekeerd ook weer niet wil zeggen dat alles wat bijvoorbeeld in een OER als fraude wordt bestempeld, ook als zodanig gekwalificeerd kan worden. 

 
